# Generated by Django 4.2.3 on 2023-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=30)),
                ('task_discription', models.TextField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
